modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="inbetweendimension"
version="1.3"
displayName="PurgatoryMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="GamingPlus_"
description='''
The Dimension Between Heaven And Hell
'''

[[dependencies.inbetweendimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.inbetweendimension]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.16]"
    ordering="NONE"
    side="BOTH"


